#!/bin/bash
#
# chkconfig: 35 90 12
# description: OrderPortal NGI Sweden server
#
# Get function from functions library
. /etc/init.d/functions

# Variables
DIR=/home/genomics.www/OrderPortal
EXE=${DIR}/orderportal/app_orderportal.py
lockfile=/var/lock/subsys/orderportal_ngi
pidfile=/var/run/orderportal_ngi.pid

# Start the service OrderPortal NGI Sweden
start() {
        echo -n $"Starting OrderPortal NGI Sweden server: "
	export PYTHONPATH="${DIR}:${PYTHONPATH}"
        ${EXE} --pidfile ${pidfile} & > /dev/null 2>&1
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

# Stop the service OrderPortal NGI Sweden
stop() {
        echo -n $"Stopping OrderPortal NGI Sweden server: "
        killproc -p ${pidfile} ${EXE}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
        return $RETVAL
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p ${pidfile} $EXE
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
