# OrderPortal: Settings file, to be edited for your instance.

### The OrderPortal instance assumes that this settings file is located at
### 'OrderPortal/site/settings.yaml'

# This file changes the default values defined in the 'settings' dictionary
# in the '__init__.py' file.

# The settings variable SITE_DIR is the directory in which this file is located.
# It is 'OrderPortal/site' by default, and should be kept so.

# The settings variable SITE_STATIC_DIR is the directory where site-specific files
# for the web interface are located. It is 'OrderPortal/site/static' and should
# also be kept so.

# tornado debug is useful only during software development.
TORNADO_DEBUG: false
# Debug logging level; may be useful for debugging the settings. Or set to 'false'.
LOGGING_DEBUG: true

# Official URL to the portal; access from the outside world.
BASE_URL: 'http://my-domain.com/'
# The following may be useful for testing on a laptop:
# BASE_URL: 'http://localhost:8880/'

# Port for the tornado server; may be different from BASE_URL if a proxy is used.
PORT: 8880

# The URL of the CouchDB server.
DATABASE_SERVER:   'http://localhost:5984/'
# The name of the database in the CouchDB server to use for OrderPortal
DATABASE_NAME:     'orderportal'
# The name of the CouchDB user account to use for creating, accessing and modifying.
DATABASE_ACCOUNT:  'orderportal_account'
# The password of the CouchDB user account.
DATABASE_PASSWORD: 'Change this to CouchDB account password'

# Salts for password and login secrets hashing.
# These *MUST* be changed for your instance, and must be kept constant once set.
COOKIE_SECRET: 'Change this to a long string of random characters.'
PASSWORD_SALT: 'Change this to another long string of random characters.'

# The name of your instance, and the support email address.
SITE_NAME:          'My Order Portal'
SITE_SUPPORT_EMAIL: 'my.email@my-domain.com'

# These files must be in the SITE_STATIC_DIR (see above).
# An absolute file path is *not* allowed.
SITE_FAVICON:     'orderportal32.png'
SITE_NAVBAR_ICON: 'orderportal32.png'  # Or set to 'null' for none.
SITE_HOME_ICON:   'orderportal144.png'
SITE_CSS_FILE:    null

# Account setup email message templates file; in SITE_DIR (see above).
ACCOUNT_MESSAGES_FILE: 'account_messages.yaml'

# Flags indicating which user account registration input fields to ask for.
ACCOUNT_PI_INFO: true
ACCOUNT_POSTAL_INFO: true
ACCOUNT_INVOICE_INFO: true
ACCOUNT_FUNDER_INFO: true

# Default country for registering account. Should be present in the COUNTRY_CODES_FILE.
ACCOUNT_DEFAULT_COUNTRY_CODES: 'SE'

# File containing country names and codes.
# Optional, may be set to null; in SITE_DIR (see above).
COUNTRY_CODES_FILE: 'country_codes.yaml'

# Terminology: change key to value in various display labels and texts.
# TERMINOLOGY:
#   order: application
#   orders: applications

# File containing the messages sent out at order status changes; in SITE_DIR (see above).
ORDER_MESSAGES_FILE: 'order_messages.yaml'

# The format for generating the sequentially numbered order identifiers.
# The prefix must be all upper-case characters.
ORDER_IDENTIFIER_FORMAT: 'MY{0:=05d}'

# Allow a report to be attached to orders.
ORDER_REPORT: true
# Allow links to be attached to orders.
ORDER_LINKS: true
# Allow tags to be set on orders.
ORDER_TAGS: true
# Allow users to set tags on orders.
ORDER_USER_TAGS: true

# The statuses to show in the orders list.
ORDERS_LIST_STATUSES:
  - submitted
  - accepted
  - processing
  - closed

# The order fields (identifiers) to show in the orders list.
# Given by list of dicts, where each dict has a required item 'identifier'
# specifying the field identifier, and an optional item 'values'
# specifying a list of values to allow filtering by.
# Orders (forms) lacking the field will just show an empty slot.
# The value is an example only; edit or comment out.
ORDERS_LIST_FIELDS:
  -
    identifier: project_pi
    label: 'Project PI'

# Fields of orders to use when doing search; only scalar fields are allowed!
ORDER_SEARCH_FIELDS:
  - project_pi

# File containing university symbols (abbreviations), names and rank in a dictionary.
# Optional, may be set to 'null'; in SITE_DIR.
UNIVERSITIES_FILE: 'swedish_universities.yaml'

# File containing subject codes file, terms in a hierarchy.
# Optional, may be set to 'null'; in SITE_DIR.
SUBJECT_TERMS_FILE: 'subject_terms.yaml'

# Sending email. No longer strictly required, but account registration and
# password setting functionality will be severely limited.
# Email server settings when available on the local machine.
EMAIL:
  HOST: 'localhost'
# Email server settings when using the Google Mail server.
# EMAIL:
#   HOST: 'smtp.gmail.com'
#   PORT: 465
#   SSL: true
#   USER: 'your.account@your.domain'
#   PASSWORD: 'your app password'

# Email address to display when for sending emails. Required.
MESSAGE_SENDER_EMAIL: '"OrderPortal Support" <support@your.domain>'
# Email address for replies if different from the sender. Optional.
MESSAGE_REPLY_TO_EMAIL: null

# Display news items in the home page.
DISPLAY_NEWS: true
DISPLAY_MAX_NEWS: 4
# Display events items in the home page.
DISPLAY_EVENTS: true
# Display the 'Information' item in the top menu.
DISPLAY_MENU_INFORMATION: true
# Display the 'Documents' item in the top menu.
DISPLAY_MENU_DOCUMENTS: true
# Display the 'Contact' item in the top menu.
DISPLAY_MENU_CONTACT: true
# Display the 'About us' item in the top menu.
DISPLAY_MENU_ABOUT_US: true
